# Generated by Django 4.2 on 2024-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='page'),
        ),
    ]
